### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by erf** [dr-soft/dred#1]
Interesting project! Are you planning OSX support?

**Comment by mackron** [comment]
Thanks. I intend on adding support for OSX eventually, but unfortunately I don't own a Mac so it's difficult to do any serious development on it right now. It'll happen eventually, but it'll be quite a while before I get to it.

Lets leave this issue open for future discussion and for anybody else who may be curious about this later on.

**Comment by r-lyeh-archived** [comment]
May I suggest GL+DearImgui as well? Cross-platform and engine embeddable too :)

**Comment by ararslan** [comment]
See #6. It's a start toward OS X support.
