### ISSUE TITLE
Help compiling: unknown GLogWriterOutput

### ISSUE THREAD

**Issue by icetbr** [dr-soft/dred#14]
Ubuntu 16.04. I'm a bit of a noob, but I do have glib installed (2.23 is the latest)

In file included from source/dred/dtk/dtk.c:205:0,
                 from source/dred/dred.c:32,
                 from source/dred/dred_main.c:18:
source/dred/dtk/dtk_window.c: In function ‘dtk_window_show_popup_menu__gtk’:
source/dred/dtk/dtk_window.c:1700:5: warning: implicit declaration of function ‘gtk_menu_popup_at_rect’ [-Wimplicit-function-declaration]
     gtk_menu_popup_at_rect(GTK_MENU(pMenu->gtk.pWidget), gtk_widget_get_window(GTK_WIDGET(pWindow->gtk.pWidget)), &rect, GDK_GRAVITY_NORTH_WEST, GDK_GRAVITY_NORTH_WEST, NULL);
     ^
In file included from source/dred/dred.c:32:0,
                 from source/dred/dred_main.c:18:
source/dred/dtk/dtk.c: At top level:
source/dred/dtk/dtk.c:800:1: error: unknown type name ‘GLogWriterOutput’
 GLogWriterOutput dtk_log_writer_handler__gtk(GLogLevelFlags level, const GLogField *fields, gsize fieldCount, gpointer pUserData)
 ^
source/dred/dtk/dtk.c:800:74: error: unknown type name ‘GLogField’
 GLogWriterOutput dtk_log_writer_handler__gtk(GLogLevelFlags level, const GLogField *fields, gsize fieldCount, gpointer pUserData)
                                                                          ^
source/dred/dtk/dtk.c: In function ‘dtk_log_writer_handler__gtk’:
source/dred/dtk/dtk.c:809:29: error: request for member ‘key’ in something not a structure or union
         if (strcmp(fields[i].key, "GLIB_DOMAIN") == 0) {
                             ^
source/dred/dtk/dtk.c:810:44: error: request for member ‘value’ in something not a structure or union
             domain = (const char*)fields[i].value;
                                            ^
source/dred/dtk/dtk.c:812:29: error: request for member ‘key’ in something not a structure or union
         if (strcmp(fields[i].key, "MESSAGE") == 0) {
                             ^
source/dred/dtk/dtk.c:813:45: error: request for member ‘value’ in something not a structure or union
             message = (const char*)fields[i].value;
                                             ^
source/dred/dtk/dtk.c:833:20: error: ‘G_LOG_WRITER_HANDLED’ undeclared (first use in this function)
             return G_LOG_WRITER_HANDLED;
                    ^
source/dred/dtk/dtk.c:833:20: note: each undeclared identifier is reported only once for each function it appears in
source/dred/dtk/dtk.c:835:20: warning: implicit declaration of function ‘g_log_writer_default’ [-Wimplicit-function-declaration]
             return g_log_writer_default(level, fields, fieldCount, pUserData);
                    ^
source/dred/dtk/dtk.c: In function ‘dtk_init__gtk’:
source/dred/dtk/dtk.c:861:9: warning: implicit declaration of function ‘g_log_set_writer_func’ [-Wimplicit-function-declaration]
         g_log_set_writer_func(dtk_log_writer_handler__gtk, pTK, NULL);
         ^

**Comment by mackron** [comment]
It looks like the errors with the GLogWriterOutput stuff is due to an incorrect version check for GLib. I've pushed a potential fix to the master branch.

Regarding the error concerning gtk_menu_popup_at_rect(), it would seem that the version of GTK you are building against is too old (that API was introduced in GTK 3.22). I will get that addressed for you and update this issue when it's done.

**Comment by mackron** [comment]
OK I've pushed some updates to the master branch. Give that another go and let me know how it works out.

Thanks for the report!

**Comment by icetbr** [comment]
Will doit on Monday. Thank you

**Comment by icetbr** [comment]
Hi, the GLogWriterOutput error is gone. The GTK 3.22 I'm weary of installing right now for lack of time/knowledge. Ubuntu 16.x uses GTK 3.18. If I have to compile and link by hand it will take too much effort for the moment. But thanks anyway.
