### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [dr-soft/dred#20]
Currently **dred** saves settings in _AppData_ (_C:\Users\UserName\AppData\Local\dred_)- I suggest a start parameter (for example- "dred.exe --portable", "dred.exe -portable", "dred.exe /portable", "dred.exe /p", etc) which forces **dred** to save settings not in _AppData_ but in program folder.

**Comment by mackron** [comment]
"dred.exe --portable" should work. It will save configs and logs relative to the executable. I did a quick test just now and it seems to work fine.

**Comment by smaragdus** [comment]
**@mackron**
Thanks.
Off-topic- would it be possible that you make **dred** detect URLs- I mean direct URL opening in default browser via double click, CTRL+click, etc.

**Comment by mackron** [comment]
URL links are planned, but it's a ways away - I need to rewrite the entire text engine at which point I'll be adding a whole bunch of new features such as syntax highlighting, multi-lingual stuff, etc. There's a lot of work in that though so it'll be a while unfortunately.

**Comment by smaragdus** [comment]
**@mackron**
I am not in a hurry, just suggested something that might be useful to others as well. Take your time and happy coding. ;)
