### ISSUE TITLE
Feature request: command line

### ISSUE THREAD

**Issue by jhave21** [dr-soft/dred#22]
hello, first great app, I like it, I would like to ask for some feature like a command line inside the editor. where I could execute commands like "python myscript.py" or "gcc -o bin.exe mycode.c". Thank you.

And looking forward for syntax highlighting :D

**Comment by mackron** [comment]
Try `!gcc -o bin.exe %`

The `!` character is used to execute a system command. The `%` character is translated to the name of the active file. (I can't remember off the top of my head if it's just the file name or the whole file path).

You can also bind that to a shortcut: `bind "Compile" "CTRL+F9" "!gcc -o bin.exe %"`

There's still a lot to do with the command line stuff, but let me know how that works!
