### ISSUE TITLE
dred 0.4.2 in windows 7

### ISSUE THREAD

**Issue by c-sanchez** [dr-soft/dred#23]
dred 0.4.2 is not working in my Windows 7 Home Basic SP1 (x86)
I have this error

> The version of this file is not compatible with the version of Windows that you are running. Check the computer system information to see if you need an x86 (32 bit) or x64 (64 bit) version of the program and then contact the provider.

![ErrorImage](https://image.ibb.co/gko20e/sshot_003.jpg)
Dred 0.4.2 is compiled for Windows x64 only?

**Comment by mackron** [comment]
Yes I'm only doing precompiled builds for 64 bit these days. I didn't think anybody was still using 32 bit, but I guess I'll need to see how I can go about doing a 32 bit build.

**Comment by mackron** [comment]
By the way, if you're a developer, dred is very easy to compile yourself (just in case that's an option for you).

**Comment by mackron** [comment]
I've decided that I don't want to be supporting pre-compiled builds of the 32-bit version anymore. It's just extra hassle for too-small of a user base. The 32-bit build is still fully supported, and I'm not intending on dropping support for it any time soon, it just means it will need to be compiled manually.
