### ISSUE TITLE
More info on README

### ISSUE THREAD

**Issue by nloveladyallen** [dr-soft/dred#5]
From the README, I have no idea whether this is a GUI or console program, what platforms are supported other than Linux, or any features that distinguish it from any other editor. I don't know who it's meant for, or why you would want to use it over Vim/Emacs/Sublime/what have you.

**Comment by ghost** [comment]
I can fix it up a bit :)

**Comment by mackron** [comment]
The readme in the source code repository is mainly for developers or people who are interested in compiling dred themselves. The website is where features are outlined. Still, you're right - there's a lot more I can add regarding platform support and whatnot so I'll leave this issue open until that's sorted out.

To answer your questions: It's a GUI program, supports Linux (GTK3) and Windows, and at the moment there aren't any real advantages to this over other more established editors, except that it's simple and lightweight. Many more features are in the pipeline though.

**Comment by ghost** [comment]
Okay I submitted a pull request with a README that addresses all of @nloveladyallen's concerns and shows an actual screenshot of the application.
